CREATE TABLE `irpf_forms` (
	`id` int AUTO_INCREMENT NOT NULL,
	`nome_cliente` varchar(255) NOT NULL,
	`cpf` varchar(14) NOT NULL,
	`data_nascimento` varchar(10) NOT NULL,
	`email` varchar(320) NOT NULL,
	`telefone` varchar(20),
	`numero_processo` varchar(50) NOT NULL,
	`vara` varchar(100) NOT NULL,
	`comarca` varchar(100) NOT NULL,
	`fonte_pagadora` varchar(255) NOT NULL,
	`cnpj` varchar(18) NOT NULL,
	`bruto_homologado` int NOT NULL,
	`tributavel_homologado` int NOT NULL,
	`numero_meses` int NOT NULL,
	`alvara_valor` int NOT NULL,
	`alvara_data` varchar(10) NOT NULL,
	`darf_valor` int NOT NULL,
	`darf_data` varchar(10) NOT NULL,
	`honorarios_valor` int NOT NULL,
	`honorarios_ano` varchar(4) NOT NULL,
	`proporcao` varchar(20) NOT NULL,
	`rendimentos_tributavel_alvara` int NOT NULL,
	`rendimentos_tributavel_honorarios` int NOT NULL,
	`base_calculo` int NOT NULL,
	`rra` varchar(20) NOT NULL,
	`ir_mensal` varchar(20) NOT NULL,
	`ir_devido` int NOT NULL,
	`irpf_restituir` int NOT NULL,
	`status_pagamento` enum('pendente','pago','cancelado') NOT NULL DEFAULT 'pendente',
	`asaas_payment_id` varchar(100),
	`asaas_status` varchar(50),
	`firebase_doc_id` varchar(100),
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `irpf_forms_id` PRIMARY KEY(`id`)
);
